tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"


brew "bat"
brew "fd"
brew "fzf"
brew "ack"
brew "tree"
brew "htop"
brew "wget"
brew "neofetch"
brew "jq"
brew "vim"
brew "tmux"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "cmacrae/formulae/spacebar"
brew "the_silver_searcher"


cask "alfred"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "visual-studio-code"
cask "zoom"
cask "font-awesome"
cask "font-awesome-terminal-fonts"
cask "font-hack-nerd-font"
